name: content-data-consumer
version: "1.0"
summary: The 'content-data-consumer' snap
description: |
    This is a simple snap example showing how to share content

grade: stable
confinement: strict

apps:
 echo:
   command: bin/echo_consumer

plugs:
  content2:
    interface: content
    content: writable-data
    target: $SNAP_COMMON

parts:
 hello:
  plugin: dump
  source: .
