name: hello-producer
version: "1.0"
summary: The 'hell-producer' snap
description: |
    This is a simple snap example showing how to share content
grade: stable
confinement: strict
type: app  #it can be gadget or framework

apps:
 echo:
   command: bin/echo_producer

slots:
  content:
    content: writable-data
    write: 
      - $SNAP_COMMON

parts:
 hello:
  plugin: dump
  source: .
