name: content-data-producer
version: "1.0"
summary: The 'content-data-producer' snap
description: |
    This is a simple snap example showing how to share content

grade: stable
confinement: strict

apps:
 echo:
   command: bin/echo_producer

slots:
  content2:
    interface: content
    content: writable-data
    write: 
      - $SNAP_COMMON

parts:
 hello:
  plugin: dump
  source: .
